package com.iotek.module;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ViewGddhDebtExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public ViewGddhDebtExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andExidIsNull() {
            addCriterion("EXID is null");
            return (Criteria) this;
        }

        public Criteria andExidIsNotNull() {
            addCriterion("EXID is not null");
            return (Criteria) this;
        }

        public Criteria andExidEqualTo(String value) {
            addCriterion("EXID =", value, "exid");
            return (Criteria) this;
        }

        public Criteria andExidNotEqualTo(String value) {
            addCriterion("EXID <>", value, "exid");
            return (Criteria) this;
        }

        public Criteria andExidGreaterThan(String value) {
            addCriterion("EXID >", value, "exid");
            return (Criteria) this;
        }

        public Criteria andExidGreaterThanOrEqualTo(String value) {
            addCriterion("EXID >=", value, "exid");
            return (Criteria) this;
        }

        public Criteria andExidLessThan(String value) {
            addCriterion("EXID <", value, "exid");
            return (Criteria) this;
        }

        public Criteria andExidLessThanOrEqualTo(String value) {
            addCriterion("EXID <=", value, "exid");
            return (Criteria) this;
        }

        public Criteria andExidLike(String value) {
            addCriterion("EXID like", value, "exid");
            return (Criteria) this;
        }

        public Criteria andExidNotLike(String value) {
            addCriterion("EXID not like", value, "exid");
            return (Criteria) this;
        }

        public Criteria andExidIn(List<String> values) {
            addCriterion("EXID in", values, "exid");
            return (Criteria) this;
        }

        public Criteria andExidNotIn(List<String> values) {
            addCriterion("EXID not in", values, "exid");
            return (Criteria) this;
        }

        public Criteria andExidBetween(String value1, String value2) {
            addCriterion("EXID between", value1, value2, "exid");
            return (Criteria) this;
        }

        public Criteria andExidNotBetween(String value1, String value2) {
            addCriterion("EXID not between", value1, value2, "exid");
            return (Criteria) this;
        }

        public Criteria andDebtAccountIsNull() {
            addCriterion("DEBT_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andDebtAccountIsNotNull() {
            addCriterion("DEBT_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andDebtAccountEqualTo(String value) {
            addCriterion("DEBT_ACCOUNT =", value, "debtAccount");
            return (Criteria) this;
        }

        public Criteria andDebtAccountNotEqualTo(String value) {
            addCriterion("DEBT_ACCOUNT <>", value, "debtAccount");
            return (Criteria) this;
        }

        public Criteria andDebtAccountGreaterThan(String value) {
            addCriterion("DEBT_ACCOUNT >", value, "debtAccount");
            return (Criteria) this;
        }

        public Criteria andDebtAccountGreaterThanOrEqualTo(String value) {
            addCriterion("DEBT_ACCOUNT >=", value, "debtAccount");
            return (Criteria) this;
        }

        public Criteria andDebtAccountLessThan(String value) {
            addCriterion("DEBT_ACCOUNT <", value, "debtAccount");
            return (Criteria) this;
        }

        public Criteria andDebtAccountLessThanOrEqualTo(String value) {
            addCriterion("DEBT_ACCOUNT <=", value, "debtAccount");
            return (Criteria) this;
        }

        public Criteria andDebtAccountLike(String value) {
            addCriterion("DEBT_ACCOUNT like", value, "debtAccount");
            return (Criteria) this;
        }

        public Criteria andDebtAccountNotLike(String value) {
            addCriterion("DEBT_ACCOUNT not like", value, "debtAccount");
            return (Criteria) this;
        }

        public Criteria andDebtAccountIn(List<String> values) {
            addCriterion("DEBT_ACCOUNT in", values, "debtAccount");
            return (Criteria) this;
        }

        public Criteria andDebtAccountNotIn(List<String> values) {
            addCriterion("DEBT_ACCOUNT not in", values, "debtAccount");
            return (Criteria) this;
        }

        public Criteria andDebtAccountBetween(String value1, String value2) {
            addCriterion("DEBT_ACCOUNT between", value1, value2, "debtAccount");
            return (Criteria) this;
        }

        public Criteria andDebtAccountNotBetween(String value1, String value2) {
            addCriterion("DEBT_ACCOUNT not between", value1, value2, "debtAccount");
            return (Criteria) this;
        }

        public Criteria andIdCardNumIsNull() {
            addCriterion("ID_CARD_NUM is null");
            return (Criteria) this;
        }

        public Criteria andIdCardNumIsNotNull() {
            addCriterion("ID_CARD_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardNumEqualTo(String value) {
            addCriterion("ID_CARD_NUM =", value, "idCardNum");
            return (Criteria) this;
        }

        public Criteria andIdCardNumNotEqualTo(String value) {
            addCriterion("ID_CARD_NUM <>", value, "idCardNum");
            return (Criteria) this;
        }

        public Criteria andIdCardNumGreaterThan(String value) {
            addCriterion("ID_CARD_NUM >", value, "idCardNum");
            return (Criteria) this;
        }

        public Criteria andIdCardNumGreaterThanOrEqualTo(String value) {
            addCriterion("ID_CARD_NUM >=", value, "idCardNum");
            return (Criteria) this;
        }

        public Criteria andIdCardNumLessThan(String value) {
            addCriterion("ID_CARD_NUM <", value, "idCardNum");
            return (Criteria) this;
        }

        public Criteria andIdCardNumLessThanOrEqualTo(String value) {
            addCriterion("ID_CARD_NUM <=", value, "idCardNum");
            return (Criteria) this;
        }

        public Criteria andIdCardNumLike(String value) {
            addCriterion("ID_CARD_NUM like", value, "idCardNum");
            return (Criteria) this;
        }

        public Criteria andIdCardNumNotLike(String value) {
            addCriterion("ID_CARD_NUM not like", value, "idCardNum");
            return (Criteria) this;
        }

        public Criteria andIdCardNumIn(List<String> values) {
            addCriterion("ID_CARD_NUM in", values, "idCardNum");
            return (Criteria) this;
        }

        public Criteria andIdCardNumNotIn(List<String> values) {
            addCriterion("ID_CARD_NUM not in", values, "idCardNum");
            return (Criteria) this;
        }

        public Criteria andIdCardNumBetween(String value1, String value2) {
            addCriterion("ID_CARD_NUM between", value1, value2, "idCardNum");
            return (Criteria) this;
        }

        public Criteria andIdCardNumNotBetween(String value1, String value2) {
            addCriterion("ID_CARD_NUM not between", value1, value2, "idCardNum");
            return (Criteria) this;
        }

        public Criteria andPriAccountIsNull() {
            addCriterion("PRI_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andPriAccountIsNotNull() {
            addCriterion("PRI_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andPriAccountEqualTo(String value) {
            addCriterion("PRI_ACCOUNT =", value, "priAccount");
            return (Criteria) this;
        }

        public Criteria andPriAccountNotEqualTo(String value) {
            addCriterion("PRI_ACCOUNT <>", value, "priAccount");
            return (Criteria) this;
        }

        public Criteria andPriAccountGreaterThan(String value) {
            addCriterion("PRI_ACCOUNT >", value, "priAccount");
            return (Criteria) this;
        }

        public Criteria andPriAccountGreaterThanOrEqualTo(String value) {
            addCriterion("PRI_ACCOUNT >=", value, "priAccount");
            return (Criteria) this;
        }

        public Criteria andPriAccountLessThan(String value) {
            addCriterion("PRI_ACCOUNT <", value, "priAccount");
            return (Criteria) this;
        }

        public Criteria andPriAccountLessThanOrEqualTo(String value) {
            addCriterion("PRI_ACCOUNT <=", value, "priAccount");
            return (Criteria) this;
        }

        public Criteria andPriAccountLike(String value) {
            addCriterion("PRI_ACCOUNT like", value, "priAccount");
            return (Criteria) this;
        }

        public Criteria andPriAccountNotLike(String value) {
            addCriterion("PRI_ACCOUNT not like", value, "priAccount");
            return (Criteria) this;
        }

        public Criteria andPriAccountIn(List<String> values) {
            addCriterion("PRI_ACCOUNT in", values, "priAccount");
            return (Criteria) this;
        }

        public Criteria andPriAccountNotIn(List<String> values) {
            addCriterion("PRI_ACCOUNT not in", values, "priAccount");
            return (Criteria) this;
        }

        public Criteria andPriAccountBetween(String value1, String value2) {
            addCriterion("PRI_ACCOUNT between", value1, value2, "priAccount");
            return (Criteria) this;
        }

        public Criteria andPriAccountNotBetween(String value1, String value2) {
            addCriterion("PRI_ACCOUNT not between", value1, value2, "priAccount");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSurplusIsNull() {
            addCriterion("SURPLUS is null");
            return (Criteria) this;
        }

        public Criteria andSurplusIsNotNull() {
            addCriterion("SURPLUS is not null");
            return (Criteria) this;
        }

        public Criteria andSurplusEqualTo(BigDecimal value) {
            addCriterion("SURPLUS =", value, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusNotEqualTo(BigDecimal value) {
            addCriterion("SURPLUS <>", value, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusGreaterThan(BigDecimal value) {
            addCriterion("SURPLUS >", value, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SURPLUS >=", value, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusLessThan(BigDecimal value) {
            addCriterion("SURPLUS <", value, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SURPLUS <=", value, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusIn(List<BigDecimal> values) {
            addCriterion("SURPLUS in", values, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusNotIn(List<BigDecimal> values) {
            addCriterion("SURPLUS not in", values, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SURPLUS between", value1, value2, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SURPLUS not between", value1, value2, "surplus");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCloseDateIsNull() {
            addCriterion("CLOSE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCloseDateIsNotNull() {
            addCriterion("CLOSE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCloseDateEqualTo(String value) {
            addCriterion("CLOSE_DATE =", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateNotEqualTo(String value) {
            addCriterion("CLOSE_DATE <>", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateGreaterThan(String value) {
            addCriterion("CLOSE_DATE >", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateGreaterThanOrEqualTo(String value) {
            addCriterion("CLOSE_DATE >=", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateLessThan(String value) {
            addCriterion("CLOSE_DATE <", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateLessThanOrEqualTo(String value) {
            addCriterion("CLOSE_DATE <=", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateLike(String value) {
            addCriterion("CLOSE_DATE like", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateNotLike(String value) {
            addCriterion("CLOSE_DATE not like", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateIn(List<String> values) {
            addCriterion("CLOSE_DATE in", values, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateNotIn(List<String> values) {
            addCriterion("CLOSE_DATE not in", values, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateBetween(String value1, String value2) {
            addCriterion("CLOSE_DATE between", value1, value2, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateNotBetween(String value1, String value2) {
            addCriterion("CLOSE_DATE not between", value1, value2, "closeDate");
            return (Criteria) this;
        }

        public Criteria andTypeCodeIsNull() {
            addCriterion("TYPE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTypeCodeIsNotNull() {
            addCriterion("TYPE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeCodeEqualTo(String value) {
            addCriterion("TYPE_CODE =", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeNotEqualTo(String value) {
            addCriterion("TYPE_CODE <>", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeGreaterThan(String value) {
            addCriterion("TYPE_CODE >", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE_CODE >=", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeLessThan(String value) {
            addCriterion("TYPE_CODE <", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("TYPE_CODE <=", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeLike(String value) {
            addCriterion("TYPE_CODE like", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeNotLike(String value) {
            addCriterion("TYPE_CODE not like", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeIn(List<String> values) {
            addCriterion("TYPE_CODE in", values, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeNotIn(List<String> values) {
            addCriterion("TYPE_CODE not in", values, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeBetween(String value1, String value2) {
            addCriterion("TYPE_CODE between", value1, value2, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeNotBetween(String value1, String value2) {
            addCriterion("TYPE_CODE not between", value1, value2, "typeCode");
            return (Criteria) this;
        }

        public Criteria andOpenDateIsNull() {
            addCriterion("OPEN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOpenDateIsNotNull() {
            addCriterion("OPEN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOpenDateEqualTo(String value) {
            addCriterion("OPEN_DATE =", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateNotEqualTo(String value) {
            addCriterion("OPEN_DATE <>", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateGreaterThan(String value) {
            addCriterion("OPEN_DATE >", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateGreaterThanOrEqualTo(String value) {
            addCriterion("OPEN_DATE >=", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateLessThan(String value) {
            addCriterion("OPEN_DATE <", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateLessThanOrEqualTo(String value) {
            addCriterion("OPEN_DATE <=", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateLike(String value) {
            addCriterion("OPEN_DATE like", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateNotLike(String value) {
            addCriterion("OPEN_DATE not like", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateIn(List<String> values) {
            addCriterion("OPEN_DATE in", values, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateNotIn(List<String> values) {
            addCriterion("OPEN_DATE not in", values, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateBetween(String value1, String value2) {
            addCriterion("OPEN_DATE between", value1, value2, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateNotBetween(String value1, String value2) {
            addCriterion("OPEN_DATE not between", value1, value2, "openDate");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(BigDecimal value) {
            addCriterion("AMOUNT =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(BigDecimal value) {
            addCriterion("AMOUNT <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(BigDecimal value) {
            addCriterion("AMOUNT >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AMOUNT >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(BigDecimal value) {
            addCriterion("AMOUNT <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AMOUNT <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<BigDecimal> values) {
            addCriterion("AMOUNT in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<BigDecimal> values) {
            addCriterion("AMOUNT not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMOUNT between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMOUNT not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andLimitIsNull() {
            addCriterion("LIMIT is null");
            return (Criteria) this;
        }

        public Criteria andLimitIsNotNull() {
            addCriterion("LIMIT is not null");
            return (Criteria) this;
        }

        public Criteria andLimitEqualTo(BigDecimal value) {
            addCriterion("LIMIT =", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitNotEqualTo(BigDecimal value) {
            addCriterion("LIMIT <>", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitGreaterThan(BigDecimal value) {
            addCriterion("LIMIT >", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LIMIT >=", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitLessThan(BigDecimal value) {
            addCriterion("LIMIT <", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LIMIT <=", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitIn(List<BigDecimal> values) {
            addCriterion("LIMIT in", values, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitNotIn(List<BigDecimal> values) {
            addCriterion("LIMIT not in", values, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LIMIT between", value1, value2, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LIMIT not between", value1, value2, "limit");
            return (Criteria) this;
        }

        public Criteria andInterestIsNull() {
            addCriterion("INTEREST is null");
            return (Criteria) this;
        }

        public Criteria andInterestIsNotNull() {
            addCriterion("INTEREST is not null");
            return (Criteria) this;
        }

        public Criteria andInterestEqualTo(BigDecimal value) {
            addCriterion("INTEREST =", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotEqualTo(BigDecimal value) {
            addCriterion("INTEREST <>", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThan(BigDecimal value) {
            addCriterion("INTEREST >", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INTEREST >=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThan(BigDecimal value) {
            addCriterion("INTEREST <", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INTEREST <=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestIn(List<BigDecimal> values) {
            addCriterion("INTEREST in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotIn(List<BigDecimal> values) {
            addCriterion("INTEREST not in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTEREST between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTEREST not between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andReturnWayCodeIsNull() {
            addCriterion("RETURN_WAY_CODE is null");
            return (Criteria) this;
        }

        public Criteria andReturnWayCodeIsNotNull() {
            addCriterion("RETURN_WAY_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andReturnWayCodeEqualTo(String value) {
            addCriterion("RETURN_WAY_CODE =", value, "returnWayCode");
            return (Criteria) this;
        }

        public Criteria andReturnWayCodeNotEqualTo(String value) {
            addCriterion("RETURN_WAY_CODE <>", value, "returnWayCode");
            return (Criteria) this;
        }

        public Criteria andReturnWayCodeGreaterThan(String value) {
            addCriterion("RETURN_WAY_CODE >", value, "returnWayCode");
            return (Criteria) this;
        }

        public Criteria andReturnWayCodeGreaterThanOrEqualTo(String value) {
            addCriterion("RETURN_WAY_CODE >=", value, "returnWayCode");
            return (Criteria) this;
        }

        public Criteria andReturnWayCodeLessThan(String value) {
            addCriterion("RETURN_WAY_CODE <", value, "returnWayCode");
            return (Criteria) this;
        }

        public Criteria andReturnWayCodeLessThanOrEqualTo(String value) {
            addCriterion("RETURN_WAY_CODE <=", value, "returnWayCode");
            return (Criteria) this;
        }

        public Criteria andReturnWayCodeLike(String value) {
            addCriterion("RETURN_WAY_CODE like", value, "returnWayCode");
            return (Criteria) this;
        }

        public Criteria andReturnWayCodeNotLike(String value) {
            addCriterion("RETURN_WAY_CODE not like", value, "returnWayCode");
            return (Criteria) this;
        }

        public Criteria andReturnWayCodeIn(List<String> values) {
            addCriterion("RETURN_WAY_CODE in", values, "returnWayCode");
            return (Criteria) this;
        }

        public Criteria andReturnWayCodeNotIn(List<String> values) {
            addCriterion("RETURN_WAY_CODE not in", values, "returnWayCode");
            return (Criteria) this;
        }

        public Criteria andReturnWayCodeBetween(String value1, String value2) {
            addCriterion("RETURN_WAY_CODE between", value1, value2, "returnWayCode");
            return (Criteria) this;
        }

        public Criteria andReturnWayCodeNotBetween(String value1, String value2) {
            addCriterion("RETURN_WAY_CODE not between", value1, value2, "returnWayCode");
            return (Criteria) this;
        }

        public Criteria andAcceptOrderIsNull() {
            addCriterion("ACCEPT_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andAcceptOrderIsNotNull() {
            addCriterion("ACCEPT_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andAcceptOrderEqualTo(String value) {
            addCriterion("ACCEPT_ORDER =", value, "acceptOrder");
            return (Criteria) this;
        }

        public Criteria andAcceptOrderNotEqualTo(String value) {
            addCriterion("ACCEPT_ORDER <>", value, "acceptOrder");
            return (Criteria) this;
        }

        public Criteria andAcceptOrderGreaterThan(String value) {
            addCriterion("ACCEPT_ORDER >", value, "acceptOrder");
            return (Criteria) this;
        }

        public Criteria andAcceptOrderGreaterThanOrEqualTo(String value) {
            addCriterion("ACCEPT_ORDER >=", value, "acceptOrder");
            return (Criteria) this;
        }

        public Criteria andAcceptOrderLessThan(String value) {
            addCriterion("ACCEPT_ORDER <", value, "acceptOrder");
            return (Criteria) this;
        }

        public Criteria andAcceptOrderLessThanOrEqualTo(String value) {
            addCriterion("ACCEPT_ORDER <=", value, "acceptOrder");
            return (Criteria) this;
        }

        public Criteria andAcceptOrderLike(String value) {
            addCriterion("ACCEPT_ORDER like", value, "acceptOrder");
            return (Criteria) this;
        }

        public Criteria andAcceptOrderNotLike(String value) {
            addCriterion("ACCEPT_ORDER not like", value, "acceptOrder");
            return (Criteria) this;
        }

        public Criteria andAcceptOrderIn(List<String> values) {
            addCriterion("ACCEPT_ORDER in", values, "acceptOrder");
            return (Criteria) this;
        }

        public Criteria andAcceptOrderNotIn(List<String> values) {
            addCriterion("ACCEPT_ORDER not in", values, "acceptOrder");
            return (Criteria) this;
        }

        public Criteria andAcceptOrderBetween(String value1, String value2) {
            addCriterion("ACCEPT_ORDER between", value1, value2, "acceptOrder");
            return (Criteria) this;
        }

        public Criteria andAcceptOrderNotBetween(String value1, String value2) {
            addCriterion("ACCEPT_ORDER not between", value1, value2, "acceptOrder");
            return (Criteria) this;
        }

        public Criteria andSurplusMonthIsNull() {
            addCriterion("SURPLUS_MONTH is null");
            return (Criteria) this;
        }

        public Criteria andSurplusMonthIsNotNull() {
            addCriterion("SURPLUS_MONTH is not null");
            return (Criteria) this;
        }

        public Criteria andSurplusMonthEqualTo(Short value) {
            addCriterion("SURPLUS_MONTH =", value, "surplusMonth");
            return (Criteria) this;
        }

        public Criteria andSurplusMonthNotEqualTo(Short value) {
            addCriterion("SURPLUS_MONTH <>", value, "surplusMonth");
            return (Criteria) this;
        }

        public Criteria andSurplusMonthGreaterThan(Short value) {
            addCriterion("SURPLUS_MONTH >", value, "surplusMonth");
            return (Criteria) this;
        }

        public Criteria andSurplusMonthGreaterThanOrEqualTo(Short value) {
            addCriterion("SURPLUS_MONTH >=", value, "surplusMonth");
            return (Criteria) this;
        }

        public Criteria andSurplusMonthLessThan(Short value) {
            addCriterion("SURPLUS_MONTH <", value, "surplusMonth");
            return (Criteria) this;
        }

        public Criteria andSurplusMonthLessThanOrEqualTo(Short value) {
            addCriterion("SURPLUS_MONTH <=", value, "surplusMonth");
            return (Criteria) this;
        }

        public Criteria andSurplusMonthIn(List<Short> values) {
            addCriterion("SURPLUS_MONTH in", values, "surplusMonth");
            return (Criteria) this;
        }

        public Criteria andSurplusMonthNotIn(List<Short> values) {
            addCriterion("SURPLUS_MONTH not in", values, "surplusMonth");
            return (Criteria) this;
        }

        public Criteria andSurplusMonthBetween(Short value1, Short value2) {
            addCriterion("SURPLUS_MONTH between", value1, value2, "surplusMonth");
            return (Criteria) this;
        }

        public Criteria andSurplusMonthNotBetween(Short value1, Short value2) {
            addCriterion("SURPLUS_MONTH not between", value1, value2, "surplusMonth");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated do_not_delete_during_merge Thu Oct 15 23:07:48 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VIEW_GDDH_DEBT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}