package com.iotek.module;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import io.swagger.annotations.ApiModel;

import java.io.Serializable;
import java.math.BigDecimal;
@ApiModel(value="ViewGddhDebt",description = "贷款信息")
public class ViewGddhDebt  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.ID
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
  //  @JsonSerialize(using= ToStringSerializer.class)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.EXID
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private String exid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.DEBT_ACCOUNT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private String debtAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.ID_CARD_NUM
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private String idCardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.PRI_ACCOUNT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private String priAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.NAME
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.SURPLUS
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private BigDecimal surplus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.STATE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.CLOSE_DATE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private String closeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.TYPE_CODE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.OPEN_DATE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private String openDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.AMOUNT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.LIMIT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private BigDecimal limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.INTEREST
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private BigDecimal interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.RETURN_WAY_CODE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private String returnWayCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.ACCEPT_ORDER
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private String acceptOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.SURPLUS_MONTH
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private Short surplusMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_GDDH_DEBT.REMARK
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.ID
     *
     * @return the value of VIEW_GDDH_DEBT.ID
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.ID
     *
     * @param id the value for VIEW_GDDH_DEBT.ID
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.EXID
     *
     * @return the value of VIEW_GDDH_DEBT.EXID
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public String getExid() {
        return exid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.EXID
     *
     * @param exid the value for VIEW_GDDH_DEBT.EXID
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setExid(String exid) {
        this.exid = exid == null ? null : exid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.DEBT_ACCOUNT
     *
     * @return the value of VIEW_GDDH_DEBT.DEBT_ACCOUNT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public String getDebtAccount() {
        return debtAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.DEBT_ACCOUNT
     *
     * @param debtAccount the value for VIEW_GDDH_DEBT.DEBT_ACCOUNT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setDebtAccount(String debtAccount) {
        this.debtAccount = debtAccount == null ? null : debtAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.ID_CARD_NUM
     *
     * @return the value of VIEW_GDDH_DEBT.ID_CARD_NUM
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public String getIdCardNum() {
        return idCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.ID_CARD_NUM
     *
     * @param idCardNum the value for VIEW_GDDH_DEBT.ID_CARD_NUM
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setIdCardNum(String idCardNum) {
        this.idCardNum = idCardNum == null ? null : idCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.PRI_ACCOUNT
     *
     * @return the value of VIEW_GDDH_DEBT.PRI_ACCOUNT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public String getPriAccount() {
        return priAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.PRI_ACCOUNT
     *
     * @param priAccount the value for VIEW_GDDH_DEBT.PRI_ACCOUNT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setPriAccount(String priAccount) {
        this.priAccount = priAccount == null ? null : priAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.NAME
     *
     * @return the value of VIEW_GDDH_DEBT.NAME
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.NAME
     *
     * @param name the value for VIEW_GDDH_DEBT.NAME
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.SURPLUS
     *
     * @return the value of VIEW_GDDH_DEBT.SURPLUS
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public BigDecimal getSurplus() {
        return surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.SURPLUS
     *
     * @param surplus the value for VIEW_GDDH_DEBT.SURPLUS
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setSurplus(BigDecimal surplus) {
        this.surplus = surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.STATE
     *
     * @return the value of VIEW_GDDH_DEBT.STATE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.STATE
     *
     * @param state the value for VIEW_GDDH_DEBT.STATE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.CLOSE_DATE
     *
     * @return the value of VIEW_GDDH_DEBT.CLOSE_DATE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public String getCloseDate() {
        return closeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.CLOSE_DATE
     *
     * @param closeDate the value for VIEW_GDDH_DEBT.CLOSE_DATE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setCloseDate(String closeDate) {
        this.closeDate = closeDate == null ? null : closeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.TYPE_CODE
     *
     * @return the value of VIEW_GDDH_DEBT.TYPE_CODE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.TYPE_CODE
     *
     * @param typeCode the value for VIEW_GDDH_DEBT.TYPE_CODE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.OPEN_DATE
     *
     * @return the value of VIEW_GDDH_DEBT.OPEN_DATE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public String getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.OPEN_DATE
     *
     * @param openDate the value for VIEW_GDDH_DEBT.OPEN_DATE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setOpenDate(String openDate) {
        this.openDate = openDate == null ? null : openDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.AMOUNT
     *
     * @return the value of VIEW_GDDH_DEBT.AMOUNT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.AMOUNT
     *
     * @param amount the value for VIEW_GDDH_DEBT.AMOUNT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.LIMIT
     *
     * @return the value of VIEW_GDDH_DEBT.LIMIT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public BigDecimal getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.LIMIT
     *
     * @param limit the value for VIEW_GDDH_DEBT.LIMIT
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setLimit(BigDecimal limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.INTEREST
     *
     * @return the value of VIEW_GDDH_DEBT.INTEREST
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public BigDecimal getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.INTEREST
     *
     * @param interest the value for VIEW_GDDH_DEBT.INTEREST
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.RETURN_WAY_CODE
     *
     * @return the value of VIEW_GDDH_DEBT.RETURN_WAY_CODE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public String getReturnWayCode() {
        return returnWayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.RETURN_WAY_CODE
     *
     * @param returnWayCode the value for VIEW_GDDH_DEBT.RETURN_WAY_CODE
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setReturnWayCode(String returnWayCode) {
        this.returnWayCode = returnWayCode == null ? null : returnWayCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.ACCEPT_ORDER
     *
     * @return the value of VIEW_GDDH_DEBT.ACCEPT_ORDER
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public String getAcceptOrder() {
        return acceptOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.ACCEPT_ORDER
     *
     * @param acceptOrder the value for VIEW_GDDH_DEBT.ACCEPT_ORDER
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setAcceptOrder(String acceptOrder) {
        this.acceptOrder = acceptOrder == null ? null : acceptOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.SURPLUS_MONTH
     *
     * @return the value of VIEW_GDDH_DEBT.SURPLUS_MONTH
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public Short getSurplusMonth() {
        return surplusMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.SURPLUS_MONTH
     *
     * @param surplusMonth the value for VIEW_GDDH_DEBT.SURPLUS_MONTH
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setSurplusMonth(Short surplusMonth) {
        this.surplusMonth = surplusMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_GDDH_DEBT.REMARK
     *
     * @return the value of VIEW_GDDH_DEBT.REMARK
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_GDDH_DEBT.REMARK
     *
     * @param remark the value for VIEW_GDDH_DEBT.REMARK
     *
     * @mbggenerated Thu Oct 15 23:07:48 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}